# Generated by Django 2.2.12 on 2021-11-07 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_auto_20211017_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gen',
            field=models.CharField(choices=[('M', 'M'), ('FM', 'FM')], max_length=60),
        ),
    ]
