# Generated by Django 2.2.12 on 2021-11-07 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_auto_20211107_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gen',
            field=models.CharField(choices=[('Accounting/Finance', 'Accounting/Finance'), ('Administration', 'Administration')], max_length=60),
        ),
    ]
