# Generated by Django 2.2.12 on 2021-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20211107_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='gedn',
            field=models.CharField(choices=[('d/Finance', 'd/Finance'), ('a', 'a')], default='baklanm', max_length=60),
        ),
        migrations.AlterField(
            model_name='info',
            name='gen',
            field=models.CharField(choices=[('Accounting/Finance', 'Accounting/Finance'), ('Administration', 'Administration')], default='sample', max_length=60),
        ),
    ]
