# Generated by Django 2.2.12 on 2021-11-07 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20211107_2019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gen',
            field=models.CharField(choices=[('M', 'M'), ('FM', 'FM')], default='sample', max_length=60),
        ),
    ]
