# Generated by Django 2.2.12 on 2021-11-07 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_auto_20211107_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='gedn',
        ),
        migrations.AddField(
            model_name='info',
            name='department',
            field=models.CharField(choices=[('Accounting/Finance', 'Accounting/Finance'), ('Administration', 'Administration'), ('Agriculture', 'Agriculture')], default='dep choice', max_length=60),
        ),
        migrations.AlterField(
            model_name='info',
            name='gen',
            field=models.CharField(choices=[('M', 'M'), ('FM', 'FM')], default='gen choice', max_length=60),
        ),
    ]
