# Generated by Django 2.2.12 on 2021-11-07 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20211107_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='gen',
            field=models.CharField(choices=[('M', 'M'), ('FM', 'FM')], default='gen choice', max_length=10),
        ),
    ]
