# Generated by Django 2.2.12 on 2021-11-09 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_remove_info_d'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Description',
        ),
    ]
