# Generated by Django 2.2.12 on 2021-11-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_delete_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='d',
            field=models.CharField(choices=[(1, 'Havana'), (2, 'New York'), (3, 'Changai'), (4, 'London')], default='', max_length=120),
        ),
    ]
