# Generated by Django 2.2.12 on 2021-11-09 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_info_d'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='d',
        ),
    ]
