# Generated by Django 2.2.12 on 2021-11-19 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0036_auto_20211112_1248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('Accounting/Finance', 'Accounting/Finance'), ('Administration', 'Administration'), ('Agriculture', 'Agriculture'), ('Art / Media', 'Art / Media'), ('Automotive service', 'Automotive service'), ('Aviation/Airport', 'Aviation/Airport'), ('Banking', 'Banking'), ('Engineering', 'Engineering'), ('Hotels, restaurants, service', 'Hotels, restaurants, service'), ('Information technology', 'Information technology'), ('Insurance', 'Insurance'), ('Marketing, Advertising, PR', 'Marketing, Advertising, PR'), ('Medical', 'Medical'), ('Quality control, environment, safety', 'Quality control, environment, safety'), ('Security', 'Security'), ('Tourism/entertainment industry', 'Tourism/entertainment industry'), ('Training courses/Educational programmes', 'Training courses/Educational programmes'), ('Beauty/Aesthetic Medicine', 'Beauty/Aesthetic Medicine'), ('Top management', 'Top management')], default='dep choice', max_length=60)),
                ('d', models.OneToOneField(default=' ', on_delete=django.db.models.deletion.CASCADE, to='base.Info')),
            ],
        ),
    ]
