# Generated by Django 2.2.12 on 2021-11-19 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0041_auto_20211119_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='description',
            name='description',
            field=models.CharField(blank=True, default='description', max_length=100, null=True),
        ),
    ]
