# Generated by Django 2.2.12 on 2021-11-19 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20211119_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.DeleteModel(
            name='Description',
        ),
    ]
