# Generated by Django 2.2.12 on 2021-11-19 22:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_auto_20211119_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='d',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Info'),
        ),
    ]
