# Generated by Django 2.2.12 on 2021-11-19 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20211119_2221'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='description',
        ),
    ]
