# Generated by Django 2.2.12 on 2021-11-19 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0046_remove_department_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='d',
        ),
        migrations.AddField(
            model_name='department',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Info'),
        ),
    ]
