# Generated by Django 2.2.12 on 2021-11-19 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_auto_20211119_2228'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(default='dep choice', max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
    ]
