# Generated by Django 2.2.12 on 2021-11-19 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20211119_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='department',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(default='', max_length=60),
        ),
    ]
