# Generated by Django 2.2.12 on 2021-11-19 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20211119_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='department',
        ),
    ]
