# Generated by Django 2.2.12 on 2021-11-20 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20211120_1010'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='students',
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.CharField(default='', max_length=200),
        ),
    ]
