# Generated by Django 2.2.12 on 2021-11-20 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20211120_1012'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enrollment',
            unique_together=set(),
        ),
    ]
