# Generated by Django 2.2.12 on 2021-11-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0057_auto_20211120_1014'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='students',
        ),
        migrations.AddField(
            model_name='department',
            name='students',
            field=models.ManyToManyField(through='base.Enrollment', to='base.Info'),
        ),
    ]
