# Generated by Django 2.2.12 on 2021-11-20 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20211120_1128'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='course',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='student',
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
