# Generated by Django 2.2.12 on 2021-11-20 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20211120_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='department',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
