# Generated by Django 2.2.12 on 2021-11-20 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20211120_1332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='person',
        ),
    ]
