# Generated by Django 2.2.12 on 2021-11-20 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_remove_department_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='person',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Info'),
        ),
    ]
