# Generated by Django 2.2.12 on 2021-11-20 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_remove_department_person'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='department',
            field=models.CharField(default='', max_length=100),
        ),
    ]
