# Generated by Django 2.2.12 on 2021-11-20 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0071_auto_20211120_1435'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
        migrations.AlterField(
            model_name='info',
            name='department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
