# Generated by Django 2.2.12 on 2021-11-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20211120_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='department',
            new_name='name',
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
