# Generated by Django 2.2.12 on 2021-11-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0073_auto_20211120_1454'),
    ]

    operations = [
        migrations.RenameField(
            model_name='department',
            old_name='name',
            new_name='department',
        ),
        migrations.RemoveField(
            model_name='info',
            name='name',
        ),
    ]
