# Generated by Django 2.2.12 on 2021-11-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_auto_20211120_1456'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Info'),
        ),
        migrations.AddField(
            model_name='info',
            name='choice',
            field=models.CharField(default='', max_length=100),
        ),
    ]
