# Generated by Django 2.2.12 on 2021-11-20 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20211120_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Department')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Info')),
            ],
        ),
    ]
