# Generated by Django 2.2.12 on 2021-11-20 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20211120_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='department',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
