# Generated by Django 2.2.12 on 2021-11-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20211120_1538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='department',
        ),
        migrations.RemoveField(
            model_name='enrollment',
            name='person',
        ),
    ]
