# Generated by Django 2.2.12 on 2021-11-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20211120_1551'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enrollment',
        ),
    ]
