# Generated by Django 2.2.12 on 2021-11-21 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20211121_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department',
        ),
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
        migrations.AddField(
            model_name='department',
            name='info',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='base.Info'),
        ),
    ]
