# Generated by Django 2.2.12 on 2021-11-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20211121_1153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=140, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='info',
            name='description',
            field=models.ManyToManyField(to='base.Description'),
        ),
    ]
