# Generated by Django 2.2.12 on 2021-11-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0088_auto_20211121_1222'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['name']},
        ),
    ]
