# Generated by Django 2.2.12 on 2021-11-21 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0091_auto_20211121_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='department',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
    ]
