# Generated by Django 2.2.12 on 2021-11-23 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_auto_20211121_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='description',
            field=models.ManyToManyField(blank=True, null=True, to='base.Description'),
        ),
    ]
