# Generated by Django 2.2.12 on 2021-11-23 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_auto_20211123_1225'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentChoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=100, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='department',
            name='name',
        ),
        migrations.RemoveField(
            model_name='description',
            name='name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='department',
        ),
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
        migrations.AddField(
            model_name='department',
            name='dep_choice',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.DepartmentChoices'),
        ),
    ]
