# Generated by Django 2.2.12 on 2021-11-23 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_auto_20211123_1314'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='dep_choice',
        ),
        migrations.AddField(
            model_name='department',
            name='name',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='info',
            name='department',
            field=models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='base.Department'),
        ),
        migrations.DeleteModel(
            name='DepartmentChoices',
        ),
    ]
