# Generated by Django 2.2.12 on 2021-11-23 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20211123_1330'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='date_of_issue',
        ),
    ]
