# Generated by Django 2.2.12 on 2021-11-23 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0099_auto_20211123_1411'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='description',
            name='name',
        ),
        migrations.RemoveField(
            model_name='info',
            name='description',
        ),
    ]
