# Generated by Django 2.2.12 on 2021-11-24 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0103_auto_20211123_1738'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['name']},
        ),
    ]
