# Generated by Django 2.2.12 on 2021-11-24 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0104_auto_20211124_0929'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={},
        ),
        migrations.AlterModelOptions(
            name='description',
            options={'ordering': ['name']},
        ),
    ]
