# Generated by Django 2.2.12 on 2021-11-24 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0105_auto_20211124_0931'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, default='', max_length=140, null=True),
        ),
    ]
