# Generated by Django 2.2.12 on 2021-11-24 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0107_remove_info_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='description',
            options={},
        ),
    ]
